// Common Dutch and Spanish meals with typical carbohydrate content per portion.
// Values are rounded averages from food composition tables (NEVO for NL, BEDCA for ES)
// and typical recipes; real portions and recipes vary, so treat them as estimates.
// Fields: c = country (nl/es/x for both), cat = category, n = names, a = extra search words,
// p = portion description, g = portion weight in grams, kh = grams of carbohydrate per portion.
window.MEALS = [
  // ---------- Nederland: ontbijt & lunch ----------
  { c: "nl", cat: "brood", n: { nl: "Bruine boterham", en: "Brown bread slice", es: "Rebanada de pan integral" }, a: "volkoren brood", p: { nl: "1 snee", en: "1 slice", es: "1 rebanada" }, g: 35, kh: 14 },
  { c: "nl", cat: "brood", n: { nl: "Witte boterham", en: "White bread slice", es: "Rebanada de pan blanco" }, a: "wit brood", p: { nl: "1 snee", en: "1 slice", es: "1 rebanada" }, g: 35, kh: 17 },
  { c: "nl", cat: "brood", n: { nl: "Boterham met hagelslag", en: "Bread with chocolate sprinkles", es: "Pan con fideos de chocolate" }, a: "chocolade vlokken", p: { nl: "1 snee + 15 g hagelslag", en: "1 slice + 15 g sprinkles", es: "1 rebanada + 15 g" }, g: 55, kh: 26 },
  { c: "nl", cat: "brood", n: { nl: "Boterham met pindakaas", en: "Bread with peanut butter", es: "Pan con crema de cacahuete" }, a: "", p: { nl: "1 snee", en: "1 slice", es: "1 rebanada" }, g: 50, kh: 16 },
  { c: "nl", cat: "brood", n: { nl: "Boterham met jam", en: "Bread with jam", es: "Pan con mermelada" }, a: "", p: { nl: "1 snee + 15 g jam", en: "1 slice + 15 g jam", es: "1 rebanada + 15 g" }, g: 50, kh: 26 },
  { c: "nl", cat: "brood", n: { nl: "Krentenbol", en: "Currant bun", es: "Bollo de pasas" }, a: "", p: { nl: "1 stuk", en: "1 bun", es: "1 unidad" }, g: 60, kh: 30 },
  { c: "nl", cat: "brood", n: { nl: "Beschuit", en: "Dutch rusk", es: "Biscote" }, a: "", p: { nl: "1 stuk", en: "1 rusk", es: "1 unidad" }, g: 10, kh: 7 },
  { c: "nl", cat: "brood", n: { nl: "Tosti ham-kaas", en: "Ham and cheese toastie", es: "Sándwich mixto" }, a: "tosti", p: { nl: "1 tosti (2 sneetjes)", en: "1 toastie (2 slices)", es: "1 sándwich" }, g: 120, kh: 32 },
  { c: "nl", cat: "brood", n: { nl: "Broodje kroket", en: "Croquette roll", es: "Bocadillo de croqueta" }, a: "", p: { nl: "1 broodje", en: "1 roll", es: "1 bocadillo" }, g: 140, kh: 45 },
  { c: "nl", cat: "brood", n: { nl: "Saucijzenbroodje", en: "Sausage roll", es: "Hojaldre de salchicha" }, a: "", p: { nl: "1 stuk", en: "1 roll", es: "1 unidad" }, g: 90, kh: 25 },
  { c: "x", cat: "brood", n: { nl: "Croissant", en: "Croissant", es: "Cruasán" }, a: "croissant", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 45, kh: 20 },
  { c: "nl", cat: "ontbijt", n: { nl: "Havermoutpap met melk", en: "Porridge with milk", es: "Gachas de avena con leche" }, a: "havermout pap", p: { nl: "1 kom (40 g havermout + 200 ml melk)", en: "1 bowl (40 g oats + 200 ml milk)", es: "1 bol (40 g avena + 200 ml leche)" }, g: 240, kh: 33 },
  { c: "nl", cat: "ontbijt", n: { nl: "Yoghurt of kwark naturel", en: "Plain yoghurt or quark", es: "Yogur natural" }, a: "kwark yoghurt", p: { nl: "1 schaaltje", en: "1 bowl", es: "1 bol" }, g: 150, kh: 6 },
  { c: "nl", cat: "ontbijt", n: { nl: "Muesli met melk", en: "Muesli with milk", es: "Muesli con leche" }, a: "cruesli granola", p: { nl: "1 kom (45 g + 150 ml melk)", en: "1 bowl (45 g + 150 ml milk)", es: "1 bol (45 g + 150 ml)" }, g: 195, kh: 37 },
  { c: "x", cat: "ontbijt", n: { nl: "Cornflakes met melk", en: "Cornflakes with milk", es: "Copos de maíz con leche" }, a: "", p: { nl: "1 kom (30 g + 150 ml melk)", en: "1 bowl (30 g + 150 ml milk)", es: "1 bol (30 g + 150 ml)" }, g: 180, kh: 32 },

  // ---------- Nederland: warme maaltijden ----------
  { c: "nl", cat: "warm", n: { nl: "Boerenkool stamppot met rookworst", en: "Kale mash with smoked sausage", es: "Puré de col rizada con salchicha" }, a: "stamppot boerenkool", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 450, kh: 45 },
  { c: "nl", cat: "warm", n: { nl: "Hutspot", en: "Hotchpotch (potato-carrot-onion mash)", es: "Puré de patata y zanahoria" }, a: "stamppot wortel", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 400, kh: 50 },
  { c: "nl", cat: "warm", n: { nl: "Zuurkool stamppot", en: "Sauerkraut mash", es: "Puré con chucrut" }, a: "", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 400, kh: 42 },
  { c: "nl", cat: "warm", n: { nl: "Andijviestamppot", en: "Endive mash", es: "Puré con endivia" }, a: "andijvie stamppot", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 400, kh: 42 },
  { c: "x", cat: "warm", n: { nl: "Gekookte aardappelen", en: "Boiled potatoes", es: "Patatas cocidas" }, a: "aardappel", p: { nl: "4 middelgrote (200 g)", en: "4 medium (200 g)", es: "4 medianas (200 g)" }, g: 200, kh: 34 },
  { c: "x", cat: "warm", n: { nl: "Aardappelpuree", en: "Mashed potatoes", es: "Puré de patatas" }, a: "puree", p: { nl: "1 portie", en: "1 portion", es: "1 ración" }, g: 200, kh: 30 },
  { c: "x", cat: "warm", n: { nl: "Rijst, gekookt", en: "Rice, cooked", es: "Arroz blanco cocido" }, a: "witte rijst", p: { nl: "1 portie (150 g gekookt)", en: "1 portion (150 g cooked)", es: "1 ración (150 g)" }, g: 150, kh: 42 },
  { c: "x", cat: "warm", n: { nl: "Pasta, gekookt", en: "Pasta, cooked", es: "Pasta cocida" }, a: "spaghetti macaroni penne", p: { nl: "1 portie (75 g droog)", en: "1 portion (75 g dry)", es: "1 ración (75 g en seco)" }, g: 190, kh: 53 },
  { c: "x", cat: "warm", n: { nl: "Spaghetti bolognese", en: "Spaghetti bolognese", es: "Espaguetis a la boloñesa" }, a: "", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 400, kh: 70 },
  { c: "nl", cat: "warm", n: { nl: "Macaroni met ham en kaas", en: "Macaroni with ham and cheese", es: "Macarrones con jamón y queso" }, a: "macaroni", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 400, kh: 72 },
  { c: "nl", cat: "warm", n: { nl: "Nasi goreng", en: "Nasi goreng (fried rice)", es: "Arroz frito indonesio" }, a: "nasi", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 350, kh: 70 },
  { c: "nl", cat: "warm", n: { nl: "Bami goreng", en: "Bami goreng (fried noodles)", es: "Fideos fritos indonesios" }, a: "bami", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 350, kh: 62 },
  { c: "nl", cat: "warm", n: { nl: "Erwtensoep", en: "Dutch pea soup", es: "Sopa de guisantes" }, a: "snert", p: { nl: "1 kom (300 ml)", en: "1 bowl (300 ml)", es: "1 bol (300 ml)" }, g: 300, kh: 25 },
  { c: "nl", cat: "warm", n: { nl: "Pannenkoek naturel", en: "Dutch pancake, plain", es: "Tortita holandesa" }, a: "pannekoek", p: { nl: "1 grote pannenkoek", en: "1 large pancake", es: "1 tortita grande" }, g: 120, kh: 35 },
  { c: "nl", cat: "warm", n: { nl: "Pannenkoek met stroop", en: "Pancake with syrup", es: "Tortita con sirope" }, a: "pannekoek", p: { nl: "1 pannenkoek + 20 g stroop", en: "1 pancake + 20 g syrup", es: "1 tortita + 20 g sirope" }, g: 140, kh: 50 },
  { c: "nl", cat: "warm", n: { nl: "Poffertjes", en: "Poffertjes (mini pancakes)", es: "Mini tortitas holandesas" }, a: "", p: { nl: "10 stuks met poedersuiker", en: "10 pieces with icing sugar", es: "10 unidades con azúcar glas" }, g: 110, kh: 42 },
  { c: "nl", cat: "warm", n: { nl: "Kibbeling", en: "Battered fish bites", es: "Pescado rebozado" }, a: "vis", p: { nl: "1 bakje", en: "1 tray", es: "1 ración" }, g: 150, kh: 15 },
  { c: "x", cat: "warm", n: { nl: "Pizza margherita", en: "Pizza margherita", es: "Pizza margarita" }, a: "pizza", p: { nl: "1 hele pizza (ca. 30 cm)", en: "1 whole pizza (approx. 30 cm)", es: "1 pizza entera (30 cm)" }, g: 330, kh: 100 },

  // ---------- Nederland: snacks & zoet ----------
  { c: "nl", cat: "snack", n: { nl: "Patat / friet (middel)", en: "Fries (medium)", es: "Patatas fritas (mediana)" }, a: "patat friet frites", p: { nl: "1 middel bakje", en: "1 medium portion", es: "1 ración mediana" }, g: 150, kh: 50 },
  { c: "nl", cat: "snack", n: { nl: "Frikandel", en: "Frikandel (minced-meat sausage)", es: "Frikandel" }, a: "", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 70, kh: 8 },
  { c: "nl", cat: "snack", n: { nl: "Kroket", en: "Croquette", es: "Croqueta holandesa" }, a: "", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 70, kh: 15 },
  { c: "nl", cat: "snack", n: { nl: "Bitterballen", en: "Bitterballen", es: "Bitterballen" }, a: "", p: { nl: "6 stuks", en: "6 pieces", es: "6 unidades" }, g: 120, kh: 20 },
  { c: "nl", cat: "zoet", n: { nl: "Stroopwafel", en: "Stroopwafel", es: "Gofre de caramelo" }, a: "", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 30, kh: 20 },
  { c: "nl", cat: "zoet", n: { nl: "Ontbijtkoek", en: "Dutch spiced cake", es: "Bizcocho de especias" }, a: "peperkoek", p: { nl: "1 plak", en: "1 slice", es: "1 rebanada" }, g: 25, kh: 17 },
  { c: "nl", cat: "zoet", n: { nl: "Speculaas", en: "Speculoos biscuit", es: "Galleta speculoos" }, a: "koekje", p: { nl: "1 koekje", en: "1 biscuit", es: "1 galleta" }, g: 10, kh: 7 },
  { c: "nl", cat: "zoet", n: { nl: "Appeltaart", en: "Dutch apple pie", es: "Tarta de manzana" }, a: "taart", p: { nl: "1 punt", en: "1 slice", es: "1 porción" }, g: 120, kh: 40 },
  { c: "nl", cat: "zoet", n: { nl: "Oliebol met poedersuiker", en: "Oliebol (Dutch doughnut)", es: "Buñuelo holandés" }, a: "oliebollen", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 65, kh: 30 },
  { c: "nl", cat: "zoet", n: { nl: "Vla", en: "Dutch custard (vla)", es: "Natillas" }, a: "pudding", p: { nl: "1 schaaltje", en: "1 bowl", es: "1 bol" }, g: 150, kh: 23 },

  // ---------- España: tapas & platos ----------
  { c: "es", cat: "warm", n: { nl: "Paella", en: "Paella", es: "Paella" }, a: "paella valenciana marisco", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 350, kh: 65 },
  { c: "es", cat: "warm", n: { nl: "Zwarte rijst (arroz negro)", en: "Black rice (arroz negro)", es: "Arroz negro" }, a: "inktvis paella", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 350, kh: 65 },
  { c: "es", cat: "warm", n: { nl: "Fideuà", en: "Fideuà (noodle paella)", es: "Fideuá" }, a: "fideua", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 350, kh: 65 },
  { c: "es", cat: "tapas", n: { nl: "Tortilla de patatas", en: "Spanish omelette", es: "Tortilla de patatas" }, a: "tortilla española omelet", p: { nl: "1 punt (pincho)", en: "1 wedge (pincho)", es: "1 pincho" }, g: 150, kh: 20 },
  { c: "es", cat: "tapas", n: { nl: "Patatas bravas", en: "Patatas bravas", es: "Patatas bravas" }, a: "aardappelen", p: { nl: "1 ración (portie)", en: "1 ración (portion)", es: "1 ración" }, g: 200, kh: 50 },
  { c: "es", cat: "tapas", n: { nl: "Croquetas", en: "Croquetas", es: "Croquetas" }, a: "kroketjes jamón", p: { nl: "4 stuks", en: "4 pieces", es: "4 unidades" }, g: 120, kh: 25 },
  { c: "es", cat: "tapas", n: { nl: "Calamares (gefrituurde inktvis)", en: "Fried calamari", es: "Calamares a la romana" }, a: "inktvisringen", p: { nl: "1 ración", en: "1 ración", es: "1 ración" }, g: 150, kh: 20 },
  { c: "es", cat: "tapas", n: { nl: "Pan con tomate", en: "Bread with tomato", es: "Pan con tomate" }, a: "pan tumaca tostada", p: { nl: "2 sneetjes stokbrood", en: "2 slices baguette", es: "2 rebanadas" }, g: 70, kh: 32 },
  { c: "es", cat: "brood", n: { nl: "Tostada met olijfolie", en: "Toast with olive oil", es: "Tostada con aceite" }, a: "ontbijt", p: { nl: "½ stokbroodje", en: "½ baguette roll", es: "media tostada" }, g: 60, kh: 30 },
  { c: "es", cat: "brood", n: { nl: "Bocadillo (belegd stokbrood)", en: "Bocadillo (baguette sandwich)", es: "Bocadillo" }, a: "jamón queso stokbrood", p: { nl: "1 bocadillo (½ baguette)", en: "1 bocadillo (½ baguette)", es: "1 bocadillo (media barra)" }, g: 160, kh: 52 },
  { c: "es", cat: "tapas", n: { nl: "Montadito", en: "Montadito (mini sandwich)", es: "Montadito" }, a: "", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 50, kh: 15 },
  { c: "es", cat: "tapas", n: { nl: "Huevos rotos (eieren met friet)", en: "Huevos rotos (eggs on fries)", es: "Huevos rotos" }, a: "", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 300, kh: 45 },
  { c: "es", cat: "tapas", n: { nl: "Ensaladilla rusa", en: "Russian salad", es: "Ensaladilla rusa" }, a: "aardappelsalade", p: { nl: "1 ración", en: "1 ración", es: "1 ración" }, g: 150, kh: 15 },
  { c: "es", cat: "tapas", n: { nl: "Albóndigas (gehaktballetjes in saus)", en: "Meatballs in sauce", es: "Albóndigas en salsa" }, a: "gehaktballen", p: { nl: "1 ración", en: "1 ración", es: "1 ración" }, g: 200, kh: 12 },
  { c: "es", cat: "tapas", n: { nl: "Pulpo a la gallega", en: "Galician octopus with potato", es: "Pulpo a la gallega" }, a: "octopus", p: { nl: "1 ración met aardappel", en: "1 ración with potato", es: "1 ración con cachelos" }, g: 250, kh: 25 },
  { c: "es", cat: "tapas", n: { nl: "Gambas al ajillo", en: "Garlic prawns", es: "Gambas al ajillo" }, a: "garnalen", p: { nl: "1 ración (zonder brood)", en: "1 ración (no bread)", es: "1 ración (sin pan)" }, g: 150, kh: 2 },
  { c: "es", cat: "tapas", n: { nl: "Jamón / manchego", en: "Cured ham / manchego cheese", es: "Jamón / queso manchego" }, a: "ham kaas iberico serrano queso", p: { nl: "1 ración (zonder brood)", en: "1 ración (no bread)", es: "1 ración (sin pan)" }, g: 80, kh: 0 },
  { c: "es", cat: "tapas", n: { nl: "Pimientos de Padrón", en: "Padrón peppers", es: "Pimientos de Padrón" }, a: "paprika", p: { nl: "1 ración", en: "1 ración", es: "1 ración" }, g: 120, kh: 4 },
  { c: "es", cat: "tapas", n: { nl: "Empanada gallega", en: "Galician pie", es: "Empanada gallega" }, a: "empanadilla", p: { nl: "1 punt", en: "1 slice", es: "1 porción" }, g: 150, kh: 45 },
  { c: "es", cat: "warm", n: { nl: "Gazpacho", en: "Gazpacho", es: "Gazpacho" }, a: "koude soep", p: { nl: "1 glas / kom (250 ml)", en: "1 glass / bowl (250 ml)", es: "1 vaso / bol (250 ml)" }, g: 250, kh: 10 },
  { c: "es", cat: "warm", n: { nl: "Salmorejo", en: "Salmorejo", es: "Salmorejo" }, a: "koude soep", p: { nl: "1 kom (200 ml)", en: "1 bowl (200 ml)", es: "1 bol (200 ml)" }, g: 200, kh: 16 },
  { c: "es", cat: "warm", n: { nl: "Lentejas (linzenstoof)", en: "Lentil stew", es: "Lentejas estofadas" }, a: "linzen", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 350, kh: 40 },
  { c: "es", cat: "warm", n: { nl: "Fabada asturiana (bonenstoof)", en: "Asturian bean stew", es: "Fabada asturiana" }, a: "bonen", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 350, kh: 38 },
  { c: "es", cat: "warm", n: { nl: "Cocido madrileño", en: "Madrid chickpea stew", es: "Cocido madrileño" }, a: "kikkererwten", p: { nl: "1 bord", en: "1 plate", es: "1 plato" }, g: 400, kh: 45 },
  { c: "es", cat: "warm", n: { nl: "Pisto (groentestoof)", en: "Pisto (vegetable stew)", es: "Pisto" }, a: "ratatouille", p: { nl: "1 portie", en: "1 portion", es: "1 ración" }, g: 200, kh: 12 },
  { c: "es", cat: "warm", n: { nl: "Sopa de ajo (knoflooksoep)", en: "Garlic soup", es: "Sopa de ajo" }, a: "", p: { nl: "1 kom", en: "1 bowl", es: "1 bol" }, g: 300, kh: 15 },

  // ---------- España: dulces ----------
  { c: "es", cat: "zoet", n: { nl: "Churros", en: "Churros", es: "Churros" }, a: "", p: { nl: "4 stuks", en: "4 pieces", es: "4 unidades" }, g: 100, kh: 40 },
  { c: "es", cat: "zoet", n: { nl: "Chocolate a la taza (dikke chocolademelk)", en: "Thick hot chocolate", es: "Chocolate a la taza" }, a: "chocolademelk", p: { nl: "1 kopje (150 ml)", en: "1 cup (150 ml)", es: "1 taza (150 ml)" }, g: 150, kh: 35 },
  { c: "es", cat: "zoet", n: { nl: "Flan", en: "Flan (caramel custard)", es: "Flan" }, a: "pudding", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 120, kh: 25 },
  { c: "es", cat: "zoet", n: { nl: "Crema catalana", en: "Crema catalana", es: "Crema catalana" }, a: "creme brulee", p: { nl: "1 schaaltje", en: "1 ramekin", es: "1 cazuelita" }, g: 150, kh: 30 },
  { c: "es", cat: "zoet", n: { nl: "Arroz con leche (rijstepap)", en: "Rice pudding", es: "Arroz con leche" }, a: "rijstpudding", p: { nl: "1 schaaltje", en: "1 bowl", es: "1 bol" }, g: 150, kh: 30 },
  { c: "es", cat: "zoet", n: { nl: "Magdalena (cakeje)", en: "Magdalena (small cake)", es: "Magdalena" }, a: "muffin", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 30, kh: 15 },
  { c: "es", cat: "zoet", n: { nl: "Torrija (wentelteefje)", en: "Torrija (Spanish French toast)", es: "Torrija" }, a: "wentelteefje", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 90, kh: 35 },
  { c: "es", cat: "zoet", n: { nl: "Turrón", en: "Turrón (nougat)", es: "Turrón" }, a: "noga", p: { nl: "1 stukje (30 g)", en: "1 piece (30 g)", es: "1 porción (30 g)" }, g: 30, kh: 15 },

  // ---------- Fruit & drinken (beide landen) ----------
  { c: "x", cat: "fruit", n: { nl: "Appel", en: "Apple", es: "Manzana" }, a: "", p: { nl: "1 middelgrote", en: "1 medium", es: "1 mediana" }, g: 150, kh: 18 },
  { c: "x", cat: "fruit", n: { nl: "Banaan", en: "Banana", es: "Plátano" }, a: "platano", p: { nl: "1 middelgrote (geschild)", en: "1 medium (peeled)", es: "1 mediano (pelado)" }, g: 120, kh: 24 },
  { c: "x", cat: "fruit", n: { nl: "Sinaasappel", en: "Orange", es: "Naranja" }, a: "", p: { nl: "1 stuk", en: "1 piece", es: "1 unidad" }, g: 150, kh: 13 },
  { c: "x", cat: "fruit", n: { nl: "Druiven", en: "Grapes", es: "Uvas" }, a: "", p: { nl: "1 handje (100 g)", en: "1 handful (100 g)", es: "1 puñado (100 g)" }, g: 100, kh: 16 },
  { c: "x", cat: "fruit", n: { nl: "Aardbeien", en: "Strawberries", es: "Fresas" }, a: "", p: { nl: "1 schaaltje (150 g)", en: "1 bowl (150 g)", es: "1 bol (150 g)" }, g: 150, kh: 9 },
  { c: "x", cat: "drinken", n: { nl: "Melk", en: "Milk", es: "Leche" }, a: "", p: { nl: "1 glas (200 ml)", en: "1 glass (200 ml)", es: "1 vaso (200 ml)" }, g: 200, kh: 9 },
  { c: "x", cat: "drinken", n: { nl: "Sinaasappelsap", en: "Orange juice", es: "Zumo de naranja" }, a: "jus d'orange", p: { nl: "1 glas (200 ml)", en: "1 glass (200 ml)", es: "1 vaso (200 ml)" }, g: 200, kh: 20 },
  { c: "x", cat: "drinken", n: { nl: "Cola (normaal, met suiker)", en: "Cola (regular, sugared)", es: "Refresco de cola (normal)" }, a: "frisdrank fanta", p: { nl: "1 blikje (330 ml)", en: "1 can (330 ml)", es: "1 lata (330 ml)" }, g: 330, kh: 35 },
  { c: "nl", cat: "drinken", n: { nl: "Chocolademelk", en: "Chocolate milk", es: "Batido de chocolate" }, a: "chocomel", p: { nl: "1 glas (200 ml)", en: "1 glass (200 ml)", es: "1 vaso (200 ml)" }, g: 200, kh: 21 },
  { c: "x", cat: "drinken", n: { nl: "Bier", en: "Beer", es: "Cerveza" }, a: "biertje caña pils", p: { nl: "1 glas (250 ml)", en: "1 glass (250 ml)", es: "1 caña grande (250 ml)" }, g: 250, kh: 8 },
  { c: "es", cat: "drinken", n: { nl: "Sangria", en: "Sangria", es: "Sangría" }, a: "", p: { nl: "1 glas (200 ml)", en: "1 glass (200 ml)", es: "1 vaso (200 ml)" }, g: 200, kh: 20 },
  { c: "x", cat: "drinken", n: { nl: "Wijn", en: "Wine", es: "Vino" }, a: "rode witte", p: { nl: "1 glas (150 ml)", en: "1 glass (150 ml)", es: "1 copa (150 ml)" }, g: 150, kh: 1 }
];
